---
- name: Install tftp-server
  ansible.builtin.dnf:
    name:
      - tftp-server
      - ipxe-bootimgs-x86
    state: present

- name: Copy undionly boot loader
  ansible.builtin.copy:
    src: /usr/share/ipxe/undionly.kpxe
    dest: /var/lib/tftpboot/undionly.kpxe
    remote_src: true
    owner: root
    group: root
    mode: '0444'

- name: Copy ipxe boot loader
  ansible.builtin.copy:
    src: /usr/share/ipxe/ipxe-x86_64.efi
    dest: /var/lib/tftpboot/ipxe.efi
    remote_src: true
    owner: root
    group: root
    mode: '0444'

- name: Enable and start tftp socket
  ansible.builtin.systemd_service:
    name: tftp.socket
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'

- name: Enable and start tftp service
  ansible.builtin.systemd_service:
    name: tftp.service
    enabled: true
    state: started
  ignore_errors: '{{ ansible_check_mode }}'
